### ISSUE TITLE
Find a fun Display font for the title of the app

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/giffium#20]
It would be nice to have a cool stylized font for the page title "Lithium".

Go ahead and find one here:
https://fonts.google.com/

Leave links as comments on this issue.

**Comment by DevvySean** [comment]
I like this one - https://fonts.google.com/specimen/Bungee+Inline?preview.text=Lithium&categoryFilters=Feeling:%2FExpressive%2FPlayful

**Comment by Baishtar** [comment]
For title I like [Novo Square](https://fonts.google.com/specimen/Nova+Square?preview.text=Lithium&query=square)

For body normally I like roboto, but it looks pretty sick with poppins too (to be clear my vote is still roboto)

**Comment by cmgriffing** [comment]
Thanks for the suggestions. For now I'm thinking Bungee Inline fits.
