### ISSUE TITLE
Feature: Gradient BG support

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/giffium#29]

**Comment by Salman2301** [comment]
Add a support for linear gradient
- Add a new column for type of background `solid` | `linear-gradient` | ...
- For now UI,
    - Select dropdown, to select type of background default to solid
    - on Linear Gradient, Show two color input box 
    - Angle of input, valid from 0 to 359°

**Comment by cmgriffing** [comment]
I think we end up needing more columns in the db.

For now, I think we need:
- `bgType`: `"solid"` | `"linearGradient"`
- `bgGradientColorStart`: string
- `bgGradientColorEnd`: string
- `bgGradientLinearDirection`: number (0 - 359)

So making sure we have those in the validation might be good too.
