### ISSUE TITLE
Bug: The Shadow checkbox is not clickable when it is unchecked

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/giffium#41]
The label is still clickable, but not the box itself.

**Comment by disdain13** [comment]
Looking into it

**Comment by disdain13** [comment]
Determined the issue could be resolved by commenting out line 420 on the Editor.tsx file. Change was made and committed, tested on local development workstation.

**Comment by disdain13** [comment]
Tested it with tab and arrow controls using space bar to activate checkbox. Test passed on local development environment.

**Comment by cmgriffing** [comment]
Thanks!
